In [13]:
import numpy as np

In [14]:
print(np.__version__)

2.2.1


In [15]:
lst = [1,2,3,4,5]

In [16]:
numbers = np.array(lst)

In [17]:
print(numbers)

[1 2 3 4 5]


In [18]:
for item in numbers:
    print(item)

1
2
3
4
5


In [19]:
lst1 = [1,2,3,4,5]
lst2 = [10,20,30,40,50]
lst3 = lst1+lst2

In [20]:
print(lst3)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [21]:
numbers + 100

array([101, 102, 103, 104, 105])

In [22]:
numbers

array([1, 2, 3, 4, 5])

In [23]:
numbers+100

array([101, 102, 103, 104, 105])

In [25]:
np.array([1,2,3,4,5])+np.array([10,11,12,13,14])

array([11, 13, 15, 17, 19])

In [26]:
lst

[1, 2, 3, 4, 5]

In [28]:
lst + np.array([10,20,20,40,50,60])

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [29]:
numbers

array([1, 2, 3, 4, 5])

In [30]:
numbers*2

array([ 2,  4,  6,  8, 10])

In [31]:
lst1

[1, 2, 3, 4, 5]

In [32]:
lst*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [33]:
lst

[1, 2, 3, 4, 5]

In [34]:
lst + lst

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [35]:
lst*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [39]:
lst2 = []
for item in lst1:
    lst2.append(item+10)

In [40]:
lst1

[1, 2, 3, 4, 5]

In [41]:
lst2

[11, 12, 13, 14, 15]

In [45]:
lst3 = [item**2 for item in lst1]

In [43]:
lst1

[1, 2, 3, 4, 5]

In [46]:
lst3

[1, 4, 9, 16, 25]

In [47]:
lst1

[1, 2, 3, 4, 5]

In [48]:
lst1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [49]:
lst2=[]

In [50]:
for item in lst1:
    lst2.append(item**2)

In [51]:
numbers

array([1, 2, 3, 4, 5])

In [52]:
numbers**2

array([ 1,  4,  9, 16, 25])

In [53]:
np.sqrt(numbers)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [54]:
np.log(numbers)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [55]:
np.tanh(numbers)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [56]:
A = np.array([10,20,30,40,50])
B = np.array([1,2,3,4,5])

In [57]:
np.dot(A,B)

np.int64(550)

In [58]:
A@B

np.int64(550)

: 

In [ ]:
mag = np.sqrt(a**)